In [1]:
import pandas as pd
from category_encoders import TargetEncoder

df_train = pd.read_csv('../data/processed/cleaned_train.csv')
df_eval = pd.read_csv('../data/processed/cleaned_eval.csv')
# df_holdout = pd.read_csv('../data/raw/holdout')

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
df_train.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Roswell,33.7338,-84.3922
1,2012-03-31,200000.0,7500.0,104.931794,79.265873,1.0,1.0,1.0,2.0,290.0,0.909091,0.000000,0.000000,PGH,15469,2012,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2441.0,41.8,20241.0,2385.0,1108.0,641.0,94600.0,1171.0,52.0,2376.0,2376.0,1018.0,105863.681174,Pittsburgh,40.4744,-79.8632
2,2012-03-31,196000.0,198000.0,122.807018,124.060150,1.0,1.0,1.0,1.0,49.0,0.989899,0.000000,0.000000,PGH,15464,2012,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,1515.0,45.1,18623.0,1508.0,692.0,484.0,79300.0,711.0,61.0,1489.0,1489.0,641.0,126572.277873,Pittsburgh,40.4744,-79.8632
3,2012-03-31,340000.0,349900.0,171.817343,242.367722,13.0,18.0,30.0,54.0,126.0,0.901457,0.153846,0.277778,BOS,2739,2012,0.0,0.0,0.0,0.0,10.0,0.0,14.0,0.0,0.0,6073.0,47.4,39312.0,6055.0,3324.0,1142.0,419600.0,3207.0,147.0,5982.0,5982.0,2794.0,352711.838012,Boston-Cambridge-Newton,42.5584,-71.1007
4,2012-03-31,51770.0,66950.0,68.638393,32.495345,7.0,7.0,6.0,19.0,111.0,0.887859,0.142857,0.000000,PGH,15461,2012,0.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4191.0,42.1,19105.0,4158.0,2033.0,501.0,72100.0,1706.0,175.0,4037.0,4037.0,1489.0,70415.266483,Pittsburgh,40.4744,-79.8632

## 'date' -> 'year', 'quart', 'month'

In [3]:
df_train['date'] = pd.to_datetime(df_train['date'])
df_train['year'] = df_train['date'].dt.year
df_train['quart'] = df_train['date'].dt.quarter
df_train['month'] = df_train['date'].dt.month

df_eval['date'] = pd.to_datetime(df_eval['date'])
df_eval['year'] = df_eval['date'].dt.year
df_eval['quart'] = df_eval['date'].dt.quarter
df_eval['month'] = df_eval['date'].dt.month

In [4]:
df_train.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng,quart,month
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Roswell,33.7338,-84.3922,1,3
1,2012-03-31,200000.0,7500.0,104.931794,79.265873,1.0,1.0,1.0,2.0,290.0,0.909091,0.000000,0.000000,PGH,15469,2012,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2441.0,41.8,20241.0,2385.0,1108.0,641.0,94600.0,1171.0,52.0,2376.0,2376.0,1018.0,105863.681174,Pittsburgh,40.4744,-79.8632,1,3
2,2012-03-31,196000.0,198000.0,122.807018,124.060150,1.0,1.0,1.0,1.0,49.0,0.989899,0.000000,0.000000,PGH,15464,2012,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,1515.0,45.1,18623.0,1508.0,692.0,484.0,79300.0,711.0,61.0,1489.0,1489.0,641.0,126572.277873,Pittsburgh,40.4744,-79.8632,1,3
3,2012-03-31,340000.0,349900.0,171.817343,242.367722,13.0,18.0,30.0,54.0,126.0,0.901457,0.153846,0.277778,BOS,2739,2012,0.0,0.0,0.0,0.0,10.0,0.0,14.0,0.0,0.0,6073.0,47.4,39312.0,6055.0,3324.0,1142.0,419600.0,3207.0,147.0,5982.0,5982.0,2794.0,352711.838012,Boston-Cambridge-Newton,42.5584,-71.1007,1,3
4,2012-03-31,51770.0,66950.0,68.638393,32.495345,7.0,7.0,6.0,19.0,111.0,0.887859,0.142857,0.000000,PGH,15461,2012,0.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4191.0,42.1,19105.0,4158.0,2033.0,501.0,72100.0,1706.0,175.0,4037.0,4037.0,1489.0,70415.266483,Pittsburgh,40.4744,-79.8632,1,3

## 'zipcode' frequency encodeding

In [5]:
zipcode_mapping = df_train['zipcode'].value_counts()

zipcode_mapping

zipcode
30002    94
2739     94
15461    94
2762     94
2770     94
15445    94
3032     94
2738     94
15473    94
15474    94
2493     94
15613    94
15610    94
2494     94
15601    94
15438    94
2538     94
2571     94
15478    94
2576     94
15618    94
15437    94
15436    94
3053     94
3077     94
15342    94
15333    94
15332    94
3079     94
15330    94
3087     94
15323    94
15321    94
3261     94
15317    94
15360    94
15363    94
3044     94
3036     94
15425    94
3037     94
15419    94
3034     94
15417    94
3038     94
15401    94
3042     94
15376    94
15367    94
15314    94
2492     94
15622    94
16025    94
16023    94
2459     94
16002    94
16001    94
2460     94
15944    94
2461     94
15697    94
15692    94
2462     94
15690    94
16028    94
2458     94
16033    94
2445     94
16057    94
16056    94
16055    94
16053    94
2446     94
16052    94
2451     94
16046    94
2452     94
16038    94
16037    94
2453     94
16049    94
2464     94
15683    94
15642    94
2476     94
15639    94
34601    94
15637    94
15636    94
2478     94
15632    94
2481     94
15627    94
15626    94
2482     94
15623    94
2474     94
15644    94
15650    94
15681    94
2465     94
15679    94
2466     94
15675    94
15672    94
15670    94
15668    94
15666    94
2468     94
15665    94
15658    94
2472     94
15656    94
2467     94
15312    94
3290     94
3867     94
15057    94
15055    94
3868     94
15052    94
3869     94
15050    94
3870     94
15046    94
15045    94
15044    94
15043    94
15059    94
15061    94
3865     94
15085    94
15084    94
15083    94
3857     94
15081    94
3858     94
15042    94
15074    94
15068    94
3861     94
15067    94
15066    94
15065    94
3862     94
15063    94
15062    94
15071    94
3856     94
3873     94
20711    94
15005    94
15003    94
20723    94
15001    94
98686    94
98685    94
20724    94
98684    94
98683    94
98682    94
98675    94
20733    94
98671    94
98665    94
98664    94
20751    94
15009    94
15010    94
15012    94
3887     94
15035    94
15034    94
15033    94
3874     94
15030    94
15027    94
15026    94
3878     94
15037    94
15025    94
15022    94
3884     94
15021    94
15019    94
3885     94
15017    94
15015    94
15014    94
15024    94
15089    94
15222    94
3824     94
15221    94
15220    94
15219    94
3825     94
15218    94
15217    94
15216    94
3826     94
15215    94
15214    94
15213    94
15212    94
3827     94
15211    94
15210    94
15209    94
3833     94
15223    94
15224    94
15225    94
3823     94
15301    94
15243    94
3801     94
15241    94
15239    94
15238    94
3811     94
15237    94
15208    94
15236    94
15234    94
3819     94
15233    94
15232    94
15229    94
3820     94
15228    94
15227    94
15226    94
15235    94
15207    94
15206    94
3835     94
15131    94
3848     94
15129    94
34602    94
15126    94
15122    94
3851     94
15120    94
15116    94
15132    94
15112    94
3852     94
15108    94
15106    94
15104    94
3854     94
15102    94
15101    94
15090    94
3855     94
15110    94
16059    94
15133    94
15135    94
15205    94
15204    94
15203    94
15202    94
3839     94
15201    94
15148    94
15147    94
3840     94
3844     94
15146    94
15144    94
3841     94
15143    94
15142    94
15140    94
15139    94
3842     94
15137    94
15136    94
15145    94
16063    94
2421     94
19067    94
19066    94
19064    94
2129     94
19063    94
19061    94
19060    94
2130     94
19057    94
19056    94
19055    94
2131     94
19054    94
19053    94
19050    94
19047    94
2132     94
19046    94
19044    94
2128     94
19070    94
19072    94
19073    94
19096    94
19095    94
2122     94
19094    94
19090    94
19087    94
2124     94
19086    94
19085    94
19043    94
19083    94
19082    94
19081    94
19079    94
2126     94
19078    94
19076    94
19075    94
2127     94
19074    94
2125     94
19102    94
34691    94
19041    94
2141     94
19014    94
19013    94
19012    94
2142     94
19010    94
19008    94
19007    94
2143     94
19006    94
19004    94
19003    94
2144     94
19002    94
19001    94
18977    94
2145     94
18976    94
19015    94
19018    94
19020    94
2140     94
19040    94
19038    94
2135     94
19036    94
19035    94
19034    94
19033    94
2136     94
19032    94
2134     94
19031    94
2138     94
19029    94
19027    94
19026    94
2139     94
19025    94
19023    94
19022    94
19021    94
19030    94
19103    94
2121     94
19104    94
19330    94
19320    94
2072     94
19317    94
19312    94
19311    94
2081     94
19310    94
19301    94
19154    94
19153    94
2090     94
19152    94
19151    94
19150    94
2093     94
19149    94
19148    94
2071     94
19333    94
19335    94
19341    94
19382    94
2056     94
19380    94
19373    94
19372    94
2061     94
19365    94
19363    94
19147    94
19362    94
19355    94
19352    94
19350    94
2066     94
19348    94
19344    94
19343    94
2067     94
19342    94
2062     94
2108     94
19146    94
19145    94
19126    94
19125    94
19124    94
2116     94
19123    94
19122    94
19121    94
19120    94
2118     94
2115     94
19119    94
19118    94
19116    94
2119     94
19115    94
19114    94
19111    94
2120     94
19107    94
19106    94
33785    94
18974    94
19127    94
19129    94
19144    94
19143    94
2109     94
19142    94
19141    94
19140    94
2110     94
19139    94
19138    94
19128    94
19137    94
19136    94
19135    94
19134    94
2113     94
19133    94
19132    94
19131    94
19130    94
2114     94
2111     94
98663    94
18972    94
2148     94
8051     94
2339     94
8049     94
8048     94
8046     94
2341     94
8045     94
8043     94
8041     94
8036     94
2343     94
8035     94
8034     94
8033     94
2346     94
8031     94
8030     94
2347     94
8052     94
8053     94
2338     94
8054     94
2322     94
8071     94
8070     94
8069     94
2324     94
8068     94
8067     94
8066     94
2330     94
8029     94
8065     94
8062     94
2332     94
8061     94
8060     94
8059     94
8057     94
2333     94
8056     94
8055     94
8063     94
8075     94
8028     94
8026     94
16242    94
16240    94
2370     94
16229    94
2379     94
16226    94
2382     94
16201    94
16136    94
2420     94
16123    94
16115    94
16066    94
2368     94
2351     94
8022     94
8021     94
8020     94
2359     94
8016     94
8015     94
2360     94
8027     94
8010     94
8009     94
2364     94
8007     94
8004     94
8003     94
2367     94
8002     94
8012     94
8077     94
8078     94
8079     94
18920    94
2169     94
18917    94
18915    94
18914    94
2170     94
18913    94
18902    94
18901    94
2171     94
18077    94
18076    94
18074    94
18073    94
2176     94
18070    94
18054    94
18041    94
2180     94
18923    94
18925    94
18929    94
2155     94
18966    94
18964    94
18960    94
2149     94
18955    94
18954    94
18951    94
2150     94
18947    94
8562     94
18944    94
18940    94
2151     94
18938    94
18934    94
2152     94
18933    94
18932    94
18930    94
18942    94
8554     94
8518     94
2184     94
8097     94
2199     94
8096     94
8094     94
8093     94
8091     94
2210     94
8090     94
33786    94
8098     94
8089     94
2215     94
8086     94
8085     94
8084     94
2301     94
8083     94
8081     94
8080     94
2302     94
8088     94
18969    94
8102     94
8103     94
8515     94
8505     94
8344     94
2186     94
8343     94
8328     94
8322     94
2188     94
2191     94
8318     94
8110     94
2189     94
8109     94
8108     94
8107     94
8106     94
2190     94
8105     94
8104     94
8312     94
19390    94
98662    94
34690    94
11423    94
11422    94
21239    94
11421    94
11420    94
11419    94
11418    94
21244    94
11417    94
11416    94
11415    94
21286    94
11414    94
11413    94
11412    94
21401    94
11411    94
11385    94
11379    94
11426    94
21237    94
11427    94
11428    94
11530    94
21229    94
11520    94
11518    94
11516    94
21230    94
11514    94
11510    94
11509    94
11378    94
21231    94
11501    94
11436    94
11435    94
21234    94
11433    94
11432    94
21236    94
11429    94
11507    94
11542    94
21403    94
11375    94
11354    94
11249    94
21628    94
11238    94
11237    94
11236    94
21638    94
11235    94
11234    94
11233    94
21651    94
11232    94
11231    94
11230    94
11229    94
21657    94
11228    94
11226    94
21623    94
11355    94
11356    94
11357    94
11374    94
21405    94
11373    94
11372    94
11370    94
21409    94
11369    94
11368    94
11367    94
11377    94
11366    94
11365    94
11364    94
11363    94
21617    94
11362    94
11361    94
11360    94
21619    94
11358    94
11225    94
11545    94
11547    94
11726    94
21213    94
11725    94
11724    94
11722    94
11721    94
21214    94
11720    94
11719    94
11718    94
21215    94
11717    94
11716    94
11715    94
21216    94
11714    94
11713    94
11710    94
11709    94
11727    94
11729    94
21212    94
11730    94
11753    94
11752    94
11751    94
11749    94
21208    94
11747    94
11746    94
11743    94
21209    94
21217    94
11742    94
11740    94
21210    94
11739    94
11738    94
11735    94
11733    94
21211    94
11732    94
11731    94
11741    94
21228    94
11706    94
11704    94
11569    94
11568    94
11566    94
21224    94
11565    94
11563    94
11561    94
21225    94
11560    94
11559    94
11558    94
21226    94
11557    94
11554    94
11553    94
21227    94
11552    94
11550    94
11548    94
21223    94
11570    94
11572    94
11575    94
21218    94
11703    94
11702    94
11701    94
21219    94
11694    94
11692    94
11691    94
11598    94
11705    94
21220    94
11590    94
11581    94
21221    94
11580    94
11579    94
11577    94
21222    94
11576    94
34607    94
11596    94
21658    94
11224    94
11223    94
46347    94
10589    94
10588    94
10583    94
46349    94
10580    94
10579    94
10578    94
10577    94
46356    94
10576    94
10573    94
10570    94
46368    94
10567    94
10566    94
10562    94
46373    94
10560    94
10590    94
10591    94
10594    94
46342    94
10707    94
10706    94
10705    94
46323    94
10704    94
10703    94
10701    94
46324    94
10607    94
10553    94
10606    94
46327    94
10604    94
10603    94
10601    94
46341    94
10598    94
10595    94
10605    94
10708    94
10552    94
46375    94
10516    94
46392    94
10514    94
10512    94
10511    94
46393    94
10510    94
10509    94
10507    94
46394    94
10506    94
10505    94
10504    94
10502    94
10501    94
10473    94
10472    94
46403    94
10520    94
10522    94
10523    94
46385    94
10549    94
10548    94
10547    94
10546    94
10543    94
10541    94
10538    94
10550    94
10537    94
10533    94
10532    94
10530    94
10528    94
46383    94
10527    94
10526    94
10524    94
10536    94
46322    94
10709    94
10710    94
11204    94
11203    94
11201    94
21776    94
11106    94
11105    94
11104    94
21784    94
11103    94
11102    94
11101    94
11096    94
21787    94
11050    94
11040    94
11030    94
21794    94
11024    94
11023    94
21771    94
11205    94
11206    94
11207    94
11222    94
21666    94
11221    94
11220    94
11219    94
11218    94
21668    94
11217    94
11216    94
11021    94
11215    94
11214    94
11213    94
11212    94
21737    94
11211    94
11210    94
11209    94
11208    94
21738    94
21723    94
21797    94
11020    94
11010    94
10962    94
46311    94
10960    94
10956    94
10954    94
46312    94
10952    94
10927    94
10964    94
10923    94
10920    94
10913    94
10901    94
46320    94
10805    94
10804    94
10803    94
46321    94
10801    94
46319    94
21207    94
10965    94
10968    94
11004    94
11003    94
34689    94
46301    94
11001    94
10994    94
10993    94
46303    94
10989    94
46310    94
10986    94
46304    94
10983    94
10980    94
10977    94
10976    94
46307    94
10974    94
34608    94
10970    94
10984    94
11754    94
11755    94
11756    94
97023    94
97022    94
97019    94
21044    94
97018    94
97017    94
97016    94
21045    94
97015    94
97013    94
97011    94
21046    94
97009    94
97008    94
97007    94
97006    94
21047    94
97005    94
97004    94
97024    94
21043    94
97027    94
97028    94
97062    94
21035    94
97060    94
97056    94
97055    94
21036    94
97054    94
97053    94
97051    94
97003    94
97049    94
97048    94
97045    94
97042    94
21040    94
97038    94
97035    94
97034    94
21042    94
97030    94
21037    94
97064    94
21048    94
34788    94
34739    94
34737    94
34736    94
21057    94
34734    94
34731    94
34715    94
34714    94
21060    94
34711    94
34705    94
33848    94
21061    94
32839    94
32837    94
32836    94
32835    94
32833    94
21056    94
34741    94
34743    94
34744    94
34787    94
21050    94
34786    94
34773    94
34772    94
34771    94
34769    94
34762    94
34797    94
34761    94
34760    94
34758    94
34756    94
21053    94
34753    94
34748    94
34747    94
34746    94
21054    94
97067    94
21034    94
97068    94
97236    94
97233    94
20777    94
97232    94
97231    94
97230    94
97229    94
20778    94
97227    94
97225    94
97224    94
20779    94
97223    94
97222    94
97221    94
20794    94
97220    94
97219    94
97218    94
97239    94
20776    94
97266    94
97267    94
20758    94
98660    94
98651    94
98648    94
98642    94
20759    94
98639    94
98629    94
98610    94
97217    94
20763    94
98606    94
98605    94
20764    94
98604    94
98601    94
97396    94
97378    94
20765    94
97347    94
98607    94
21001    94
97216    94
97215    94
97123    94
34604    94
97119    94
21028    94
97116    94
97115    94
97114    94
21029    94
21017    94
97113    94
97106    94
21030    94
97101    94
97089    94
97086    94
97080    94
21032    94
97078    94
97070    94
97111    94
32832    94
97124    94
97128    94
97214    94
21009    94
97213    94
97212    94
97211    94
21012    94
97210    94
97209    94
97206    94
97127    94
97205    94
97203    94
97202    94
97201    94
21014    94
97148    94
97140    94
97133    94
21015    94
97132    94
21013    94
98661    94
32829    94
32828    94
21152    94
11948    94
11946    94
11944    94
21153    94
11942    94
11941    94
11940    94
11939    94
21154    94
11937    94
11935    94
11934    94
21155    94
11933    94
11932    94
11930    94
11901    94
11949    94
11950    94
11952    94
21146    94
11971    94
11968    94
21133    94
11967    94
11965    94
11964    94
21136    94
11963    94
11804    94
21140    94
11960    94
11959    94
11958    94
21144    94
11957    94
11955    94
11954    94
11953    94
11961    94
11975    94
11803    94
21157    94
11776    94
21201    94
11772    94
11771    94
11770    94
21202    94
11769    94
11768    94
11767    94
21204    94
11766    94
11765    94
11764    94
11763    94
21205    94
11762    94
11758    94
11757    94
21206    94
11777    94
11778    94
11779    94
21163    94
11798    94
11797    94
11796    94
21158    94
11795    94
11793    94
11792    94
21160    94
11791    94
11801    94
11790    94
11788    94
21161    94
11787    94
11786    94
11784    94
21162    94
11783    94
11782    94
11780    94
11789    94
21132    94
11976    94
11977    94
21084    94
32804    94
32803    94
32801    94
21085    94
32798    94
32792    94
32789    94
21087    94
32784    94
32779    94
32778    94
32776    94
21090    94
32773    94
32771    94
32767    94
21093    94
32766    94
32805    94
32806    94
32807    94
32808    94
32827    94
32826    94
21075    94
32825    94
32824    94
32822    94
21076    94
32821    94
32820    94
32765    94
32819    94
32817    94
32814    94
32812    94
21078    94
32811    94
32810    94
32809    94
21082    94
32818    94
32757    94
21102    94
32751    94
18458    94
21117    94
18451    94
18445    94
18435    94
21120    94
18428    94
18426    94
18425    94
18464    94
18371    94
18337    94
18336    94
18328    94
21128    94
18324    94
12563    94
11980    94
21131    94
11978    94
21122    94
21074    94
34606    94
21114    94
32750    94
32746    94
32736    94
21104    94
32735    94
32732    94
32730    94
21108    94
32726    94
32102    94
32714    94
21111    94
32709    94
32708    94
32707    94
32703    94
21113    94
32702    94
32701    94
32159    94
32712    94
19401    94
2054     94
19403    94
98270    94
98258    94
98256    94
30314    94
98252    94
98251    94
98241    94
30315    94
98223    94
98208    94
30316    94
98206    94
98204    94
98203    94
30317    94
98201    94
98199    94
98198    94
98271    94
30313    94
98272    94
98275    94
30308    94
98333    94
98332    94
33774    94
98329    94
30309    94
98328    94
98327    94
98323    94
98188    94
98321    94
98304    94
98303    94
98296    94
30311    94
98294    94
98292    94
98290    94
30312    94
30310    94
98335    94
30318    94
98177    94
98115    94
98112    94
98109    94
30331    94
98108    94
98107    94
98106    94
98105    94
98104    94
98103    94
98102    94
30337    94
98101    94
98092    94
98087    94
30338    94
98077    94
98075    94
30329    94
98116    94
98117    94
98118    94
98168    94
30319    94
98166    94
98164    94
98155    94
30324    94
98148    94
98146    94
98144    94
98178    94
98136    94
98134    94
98133    94
98126    94
30327    94
98125    94
98122    94
98121    94
30328    94
98119    94
30326    94
98074    94
98338    94
30307    94
30276    94
94038    94
94037    94
94030    94
30277    94
94028    94
94027    94
94025    94
94020    94
30281    94
94019    94
94018    94
94015    94
30288    94
94014    94
94010    94
94005    94
34698    94
30290    94
94044    94
94060    94
94061    94
30274    94
94112    94
94111    94
30265    94
94110    94
94109    94
94108    94
94107    94
30268    94
94105    94
94002    94
94104    94
30269    94
94102    94
94080    94
94070    94
30273    94
94066    94
94065    94
94063    94
94062    94
94103    94
98349    94
98580    94
98498    94
98396    94
98394    94
30297    94
98391    94
98390    94
98388    94
30303    94
98387    94
98375    94
30305    94
98374    94
98373    94
98372    94
98371    94
30306    94
98360    94
98354    94
98351    94
98402    94
98403    94
30296    94
98404    94
30291    94
98467    94
98466    94
98465    94
30292    94
98446    94
98445    94
98444    94
30293    94
98499    94
98443    94
98422    94
98418    94
30294    94
98409    94
98408    94
98407    94
30295    94
98406    94
98405    94
98424    94
30339    94
98072    94
98070    94
31816    94
92065    94
92064    94
92061    94
31830    94
92060    94
92058    94
76527    94
92057    94
92056    94
92054    94
92040    94
76530    94
92037    94
92036    94
92029    94
76537    94
92028    94
92066    94
92067    94
92069    94
33776    94
92105    94
92104    94
30663    94
92103    94
92102    94
92101    94
30666    94
92091    94
92027    94
92086    94
30680    94
92083    94
92082    94
92081    94
92078    94
31064    94
92075    94
92071    94
92070    94
92084    94
92106    94
92026    94
92025    94
91935    94
91934    94
91932    94
78616    94
91916    94
91915    94
91914    94
78617    94
91913    94
91911    94
91910    94
78619    94
91906    94
91905    94
91902    94
91901    94
78620    94
91941    94
91942    94
91945    94
78613    94
92024    94
92021    94
92020    94
76578    94
92019    94
92014    94
92011    94
78602    94
92010    94
76574    94
92009    94
78610    94
92007    94
92003    94
91978    94
91977    94
78612    94
91963    94
91962    94
91950    94
92008    94
30656    94
92107    94
92108    94
98036    94
98034    94
98033    94
98032    94
30349    94
98031    94
98030    94
98029    94
30350    94
98028    94
98027    94

In [6]:
df_train['zipcode_freq'] = df_train['zipcode'].map(zipcode_mapping)

df_eval['zipcode_freq'] = df_eval['zipcode'].map(zipcode_mapping).fillna(0)
# df_eval = df_eval[df_eval['zipcode_freq'].isnull() == False]
df_eval[df_eval['zipcode_freq'].isnull()]

Empty DataFrame
Columns: [date, median_sale_price, median_list_price, median_ppsf, median_list_ppsf, homes_sold, pending_sales, new_listings, inventory, median_dom, avg_sale_to_list, sold_above_list, off_market_in_two_weeks, city, zipcode, year, bank, bus, hospital, mall, park, restaurant, school, station, supermarket, Total Population, Median Age, Per Capita Income, Total Families Below Poverty, Total Housing Units, Median Rent, Median Home Value, Total Labor Force, Unemployed Population, Total School Age Population, Total School Enrollment, Median Commute Time, price, city_full, lat, lng, quart, month, zipcode_freq]
Index: []

## Target encoding ('city_full' and 'price')

In [7]:
te = TargetEncoder(cols=['city_full'])

df_train['city_encoded'] = te.fit_transform(df_train['city_full'], df_train['price'])
df_eval['city_encoded'] = te.transform(df_eval['city_full'])

print(df_train[['city_full', 'city_encoded']].head())

                       city_full   city_encoded
0  Atlanta-Sandy Springs-Roswell  192627.058387
1                     Pittsburgh  131828.753854
2                     Pittsburgh  131828.753854
3        Boston-Cambridge-Newton  472075.429542
4                     Pittsburgh  131828.753854

## Drop unused columns

In [8]:
col_drops = ['date', 'zipcode', 'city_full', 'city', 'median_sale_price']
df_train.drop( columns = col_drops, inplace=True)
df_eval.drop( columns = col_drops, inplace=True)

df_train.head()
df_eval.head()

,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,lat,lng,quart,month,zipcode_freq,city_encoded
0,168450.0,123.333333,109.899800,35.0,30.0,34.0,37.0,50.0,0.954732,0.171429,0.300000,2020,3.0,0.0,2.0,0.0,68.0,30.0,60.0,5.0,14.0,10849.0,42.1,27037.0,10795.0,4598.0,964.0,169000.0,5690.0,414.0,10573.0,10573.0,5089.0,1.648397e+05,41.6675,-87.9597,1,1,94.0,221986.823469
1,139000.0,94.691957,111.311054,61.0,81.0,83.0,54.0,10.0,0.963039,0.098361,0.469136,2020,35.0,5.0,4.0,3.0,139.0,259.0,86.0,1.0,8.0,20624.0,36.6,30324.0,19423.0,10164.0,802.0,132400.0,10479.0,552.0,19809.0,19809.0,9383.0,1.321643e+05,39.0811,-84.4646,1,1,94.0,150644.162953
2,1600000.0,1386.111111,1801.309410,134.0,151.0,210.0,563.0,188.0,0.971567,0.037313,0.006623,2020,344.0,11.0,26.0,8.0,404.0,2054.0,324.0,114.0,172.0,62541.0,43.3,126937.0,60995.0,41353.0,2346.0,1218900.0,37308.0,1440.0,60206.0,60206.0,31554.0,1.494755e+06,40.7222,-74.0225,1,1,94.0,531812.641036
3,550000.0,233.574442,243.803182,21.0,16.0,15.0,34.0,97.0,0.963443,0.095238,0.062500,2020,0.0,0.0,1.0,0.0,14.0,0.0,10.0,0.0,0.0,5132.0,50.2,53105.0,4987.0,2481.0,1279.0,483500.0,2400.0,104.0,5036.0,5036.0,1957.0,4.882322e+05,42.5584,-71.1007,1,1,94.0,472075.429542
4,219900.0,183.644102,191.074971,14.0,18.0,16.0,15.0,42.0,0.961928,0.285714,0.388889,2020,13.0,0.0,1.0,4.0,88.0,26.0,78.0,4.0,9.0,5103.0,38.8,29393.0,5093.0,1848.0,956.0,178700.0,2682.0,197.0,4934.0,4934.0,2425.0,1.944681e+05,41.6675,-87.9597,1,1,94.0,221986.823469

## Save featured-engineer datasets

In [9]:
df_train.to_csv('../data/processed/feature_engineered_train.csv', index=False)
df_eval.to_csv('../data/processed/feature_engineered_eval.csv', index=False)